### ISSUE TITLE
Add an acceptLicense parameter

### ISSUE THREAD

**Issue by chyt** [MicroShed/boost#114]
In 0.1.1 we have lifted the requirement to accept feature licenses for any Maven Central features. However, in the future if users may need to accept a license for a commercial feature they are using with their boosted Liberty runtime, we should add an `acceptLicense` configuration parameter so that they can do so.

**Comment by scottkurz** [comment]
@chyt can you please help me understand the use case here?    When would someone need to have `acceptLicense` specified on the LMP invocation?

**Comment by chyt** [comment]
The user needs to accept licenses when using features that aren't on Maven Central (those are all EPL license). My understanding is that this is for the features that people pay for, if they are using any of them they will need to accept the license. We shouldn't be doing that for them automatically in the LMP invoker configuration since this needs to be an active decision that the user is making.

**Comment by scottkurz** [comment]
Makes sense..thanks,

**Comment by scottkurz** [comment]
Not actively working.. let's close for now.
