### ISSUE TITLE
Support MicroProfile 2.0.x

### ISSUE THREAD

**Issue by cherylking** [MicroShed/boost#141]
The MicroProfile 2.0 release is based on Java EE 8 APIs. The following is copied from https://github.com/eclipse/microprofile/releases:

The content for MicroProfile 2.0 will be MicroProfile 1.4 plus Java EE 8 versions of the base features. Thus, the complete list of functional components for MicroProfile 2.0 includes...

MicroProfile Config 1.3
MicroProfile Fault Tolerance 1.1
MicroProfile Health Check 1.0
MicroProfile JWT Authentication 1.1
MicroProfile Metrics 1.1
MicroProfile OpenAPI 1.0
MicroProfile OpenTracing 1.1
MicroProfile Rest Client 1.1
CDI 2.0
Common Annotations 1.3
JAX-RS 2.1
JSON-B 1.0
JSON-P 1.1

**Comment by scottkurz** [comment]
We have basic support for MP 2.0 so marking this resolved.
