### ISSUE TITLE
Figure out boost-boosters project structure for release

### ISSUE THREAD

**Issue by chyt** [MicroShed/boost#187]
As is, the boosters project uses the invoker plugin to build each booster. However this will not work for the booster releases since it only runs the `install` goal and is missing release configuration. We need to figure out a scalable way to manage these projects both for building and releasing.

**Comment by scottkurz** [comment]
Not saying we've figured everything out..but we haven't been actively working this issue and we just did a release of 0.2.1.  Closing for now.
