### ISSUE TITLE
Updated README with usage instruction

### ISSUE THREAD

**Issue by yeekangc** [MicroShed/boost#373]
Update the repo landing page with information how a developer can start using Boost.

We can point to the wiki as appropriate but we should make it easy and obvious for developers on how they can get started.

The contributor information can come after.

**Comment by scottkurz** [comment]
Hi @ahegde3 .. I was going to close this issue just now and saw your comment.   

Thank you for the offer.   

Let me ask, I know we don't have a lot of documentation.. is there an area that you were specifically interested in or planning to work on?

**Comment by scottkurz** [comment]
Closing fixed by https://github.com/MicroShed/boost/pull/398
